### PR TITLE
Create vue sensor status page

### PR DESCRIPTION
**Pull request by emilytrau**
image

I'd love to get everyone's opinion on how readable the code is, and whether it is simple enough to extend in the future without a lot of experience in Vue.

### CODE REVIEW

**Comment by emilytrau** [comment]
I decided to write a React version for comparison. Personally I prefer it
https://github.com/monash-human-power/dashboard/tree/react

**Comment by harsilspatel** [comment]
make sure you're getting enough sleep Angus! :D

**Review by harsilspatel — COMMENTED** [review]
Looks good to me, can't wait to checkout the new website, great work, now get some rest @angustrau :D

**Review by harsilspatel — APPROVED** [review]

**Comment by harsilspatel** [comment]
woah wtf, i just read the React version comment, that's incredible Angus, like seriously, too good! ^_^

**Review by hallgchris — APPROVED** [review]
Looks very cool, I think I could get my head around this! Haven't looked at the react properly yet.

Is the intention to keep frontend/backend separate or will they be merged together like they were before?

**Comment by emilytrau** [comment]
@hallgchris yep, they will be kept separate. The backend will be configured to serve the frontend's build output as static files. This will make it easier to refactor the backend in the future.

**Comment by khanguslee** [comment]
Good job as always! I may be biased (since I've worked with React a lot more), but looking at the Vue code kinda hurts my eyes compared to the code in your `react` branch. I just don't like how the html, js and css code are in the same file and I can see it get messy (expecially with inexperienced programmers)

 Going forward, happy to merge this branch into the main `vue` branch, but I think moving towards React is the way to go. Expecially since how BOOSTERS will also be using React.

**Review by khanguslee — APPROVED** [review]

**Review by maanika — APPROVED** [review]

**Comment by emilytrau** [comment]
I'm merging this branch, but going forward the rewrite will be in React, and be developed in the `react` branch instead.

**Pull request merged**
