### PR TITLE
Fix heroku deploy

### PR DESCRIPTION
**Pull request by emilytrau**
## Description

This PR fixes some config files that got removed when moving the server project files. Along with it, I've made some changes to the Heroku config to enable review apps.

## Screenshots

N/A

## Steps to Test

[Production](http://mhp-board.herokuapp.com)
[Staging](http://mhp-board.herokuapp.com)
There should also be a review app generated for this PR.

### CODE REVIEW

**Comment by khanguslee** [comment]
If we really wanted to a prod/staging environment, I think using the Github Flow would be more aligned to what most companies in industry do. https://guides.github.com/introduction/flow/

Master as prod,  development branch for staging. Thoughts?

EDIT: I meant Git flow.
https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow

**Comment by khanguslee** [comment]
https://lucamezzalira.com/2014/03/10/git-flow-vs-github-flow/

Definitely something we should discuss. Let me know of your thoughts. Open for ideas!

**Comment by emilytrau** [comment]
I think we're most of the way there, so why not. Although the continuous deployment of the GitHub Flow is more inline with our release process I reckon

**Comment by emilytrau** [comment]
On second thought, we don't really need a staging environment. The dashboard doesn't have any regular users that depend on it being stable. Perhaps we should go back to deploying from master, but keeping the review apps.

**Comment by khanguslee** [comment]
> On second thought, we don't really need a staging environment. The dashboard doesn't have any regular users that depend on it being stable. Perhaps we should go back to deploying from master, but keeping the review apps.

Yeah you're right. We really only use the public dashboards on testing days (for now). But later on once V3 is done, dashboard will be used more regularly!

**Review by khanguslee — APPROVED** [review]
LGTM!

**Pull request merged**
