### PR TITLE
add contribution bot config

### PR DESCRIPTION
**Pull request by harsilspatel**

### CODE REVIEW

**Comment by hallgchris** [comment]
What does this do?

**Comment by harsilspatel** [comment]
oh sorry, i should've mentioned that somewhere. setting it up to recognise users' contributions ;)

Checkout their [website](https://allcontributors.org/docs/en/overview) for more info

**Comment by harsilspatel** [comment]
also, don't approve just yet, i'll update things and request reviews :)

**Comment by khanguslee** [comment]
Update on this @harsilspatel ?

**Comment by harsilspatel** [comment]
this has been taken care of, closing this PR!

**Pull request closed without merging**
