### PR TITLE
Create pull request template

### PR DESCRIPTION
**Pull request by khanguslee**
A fairly simple PR template. Am I missing anything else? Once we finalise on a template, I will create the same template for all repos!

### CODE REVIEW

**Review by emilytrau — DISMISSED** [review]

**Review by Blake-Haydon — DISMISSED** [review]
Looks good, just want to check that its only 7 lines

**Review by hallgchris — COMMENTED** [review]
For inspiration, here's Rome2rio's PR template

[removed 17/01/2020]

Quite extra, and no one uses the checkboxes anyway, but I feel like we could take a bit from it. I find that although it's nice to think that we'd remember to do things like include screenshots or whatever, it's easy to forget and I do find it useful to have right in front of me.

Perhaps in the Description section we could include a reminder that there should be screenshots if relevant, and state that there should be one conceptual change (if that can be tied into the wording in some non-awkward way).

In the testing section, a small reminder to write automated tests, if relevant, could also be good.

Finally, what do you think about a pre-merge checklist? Could be all on one line, specifying that all feedback should be addressed, will squash and merge, whatever.

Idk, maybe this is all too extra :sweat_smile: thoughts people?

Also if I remember, I'll remove the excerpt from Rome2rio's repo in a few days. Probably not the best idea go around posting that

**Comment by khanguslee** [comment]
Definitely agree with the checkboxes as we will just click it without reading it.

> Perhaps in the Description section we could include a reminder that there should be screenshots if relevant, and state that there should be one conceptual change (if that can be tied into the wording in some non-awkward way).

My workplace does that atm as well, so I'll add a screenshots section (if relevant)

> In the testing section, a small reminder to write automated tests, if relevant, could also be good.

Unfortunately we aren't at the stage where we have automated testing. With Github Actions/Travis this will be done automatically anyway.

> Finally, what do you think about a pre-merge checklist? Could be all on one line, specifying that all feedback should be addressed, will squash and merge, whatever.

I think this should be known already by submitting a PR.

Good suggestions though!

**Review by maanika — DISMISSED** [review]

**Review by emilytrau — DISMISSED** [review]

**Review by hallgchris — DISMISSED** [review]
Add the screenshots section and LGTM

**Review by emilytrau — APPROVED** [review]

**Pull request merged**
